Repository Facepunch/garrysmod, pull requests merged in 2018-05, with the labels that each got.

#1486 [TTT] Make first-person spectating not draw the label of the spectated player
  garrysmod/gamemodes/terrortown/entities/weapons/weapon_zm_carry.lua
  garrysmod/gamemodes/terrortown/gamemode/cl_targetid.lua
Labels: TTT

#1438 Improved scratch decimals support
  garrysmod/lua/vgui/dnumberscratch.lua
Labels: improvement

#1340 Small PrintTable() iteration optimisation
  garrysmod/lua/includes/util.lua
Labels: improvement

#1481 Fix weapon_medkit
  garrysmod/lua/weapons/weapon_medkit.lua
Labels: fix, improvement

#1167 Replaced SortedPairs* and RandomPairs with better implementations
  garrysmod/lua/includes/extensions/table.lua
Labels: improvement

#1491 TTT: Fix always playing zoom-out animation
  garrysmod/gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
Labels: TTT
