Repository Facepunch/garrysmod, pull requests merged in 2019-09, with the labels that each got.

#1586 Do not discipline a weapon's new table type values when inheriting the BaseClass table
  garrysmod/lua/includes/modules/weapons.lua
Labels: fix

#1559 alt to walk in default config
  garrysmod/cfg/config_default.cfg
Labels: improvement

#1504 cleaned up animations file
  garrysmod/gamemodes/base/gamemode/animations.lua
Labels: improvement

#1502 Remove hardcoded ammo type from SWEP:ShootBullet
  garrysmod/gamemodes/base/entities/weapons/weapon_base/shared.lua
Labels: addition

#1611 [TTT] Stop bleeding on respawn/death
  garrysmod/gamemodes/terrortown/gamemode/player.lua
  garrysmod/gamemodes/terrortown/gamemode/util.lua
Labels: TTT

#1610 pairs -> ipairs
  garrysmod/gamemodes/terrortown/entities/entities/base_ammo_ttt.lua
  garrysmod/gamemodes/terrortown/entities/entities/ttt_c4/shared.lua
  garrysmod/gamemodes/terrortown/entities/entities/ttt_confgrenade_proj.lua
  garrysmod/gamemodes/terrortown/entities/entities/ttt_cse_proj.lua
  garrysmod/gamemodes/terrortown/entities/entities/ttt_damageowner.lua
  garrysmod/gamemodes/terrortown/entities/entities/ttt_flame.lua
  garrysmod/gamemodes/terrortown/entities/entities/ttt_traitor_check.lua
  garrysmod/gamemodes/terrortown/entities/entities/ttt_weapon_check.lua
  garrysmod/gamemodes/terrortown/entities/weapons/weapon_ttt_flaregun.lua
  garrysmod/gamemodes/terrortown/entities/weapons/weapon_ttt_teleport.lua
  garrysmod/gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
  garrysmod/gamemodes/terrortown/entities/weapons/weapon_zm_carry.lua
  garrysmod/gamemodes/terrortown/gamemode/admin.lua
  garrysmod/gamemodes/terrortown/gamemode/cl_equip.lua
  garrysmod/gamemodes/terrortown/gamemode/cl_init.lua
  garrysmod/gamemodes/terrortown/gamemode/cl_lang.lua
  garrysmod/gamemodes/terrortown/gamemode/cl_msgstack.lua
  garrysmod/gamemodes/terrortown/gamemode/cl_popups.lua
  garrysmod/gamemodes/terrortown/gamemode/cl_targetid.lua
  garrysmod/gamemodes/terrortown/gamemode/cl_tbuttons.lua
  garrysmod/gamemodes/terrortown/gamemode/cl_transfer.lua
  garrysmod/gamemodes/terrortown/gamemode/ent_replace.lua
  garrysmod/gamemodes/terrortown/gamemode/gamemsg.lua
  garrysmod/gamemodes/terrortown/gamemode/init.lua
  garrysmod/gamemodes/terrortown/gamemode/karma.lua
  garrysmod/gamemodes/terrortown/gamemode/lang_shd.lua
  garrysmod/gamemodes/terrortown/gamemode/player.lua
  garrysmod/gamemodes/terrortown/gamemode/player_ext_shd.lua
  garrysmod/gamemodes/terrortown/gamemode/radar.lua
  garrysmod/gamemodes/terrortown/gamemode/scoring.lua
  garrysmod/gamemodes/terrortown/gamemode/traitor_state.lua
  garrysmod/gamemodes/terrortown/gamemode/util.lua
  garrysmod/gamemodes/terrortown/gamemode/vgui/sb_main.lua
Labels: TTT

#996 Add Unpack, SetUnpacked, and ToTable to Color
  garrysmod/lua/includes/util/color.lua
Labels: addition
