Repository Facepunch/garrysmod, pull requests merged in 2019-03, with the labels that each got.

#1538 Create table.IsEmpty
  garrysmod/lua/includes/extensions/table.lua
Labels: addition

#1544 add nocollide to weld tool
  garrysmod/gamemodes/sandbox/entities/weapons/gmod_tool/stools/weld.lua
Labels: addition

#1542 Remove MarkupObject:Create()
  garrysmod/lua/includes/modules/markup.lua
Labels: improvement

#998 Add Tooltip accessors
  garrysmod/lua/includes/extensions/client/panel.lua
Labels: addition

#1394 make Player:SetPData and Player:RemovePData actually return a boolean
  garrysmod/lua/includes/extensions/player.lua
Labels: addition

#1569 [TTT] Optimizations using table.IsEmpty
  garrysmod/gamemodes/terrortown/gamemode/cl_awards.lua
  garrysmod/gamemodes/terrortown/gamemode/gamemsg.lua
  garrysmod/gamemodes/terrortown/gamemode/player.lua
Labels: TTT

#1570 Another TTT table.IsEmpty optimisation
  garrysmod/gamemodes/terrortown/gamemode/player.lua
Labels: TTT

#1356 Added SetInterval and GetInterval to DNumberWang
  garrysmod/lua/vgui/dnumberwang.lua
Labels: addition

#1514 ENT:BeingLookedAtByLocalPlayer optimisation
  garrysmod/gamemodes/sandbox/entities/entities/base_gmodentity.lua
Labels: improvement
