Repository Facepunch/garrysmod, pull requests merged in 2019-06, with the labels that each got.

#1494 NoDrop NPC spawn fix
  garrysmod/gamemodes/sandbox/gamemode/commands.lua
  garrysmod/lua/autorun/base_npcs.lua
Labels: fix

#1460 Add list.HasEntry
  garrysmod/lua/includes/modules/list.lua
Labels: addition

#1428 Add min, max args to Vector/AngleRand
  garrysmod/lua/includes/util.lua
Labels: addition

#1426 math.Clamp efficiency
  garrysmod/lua/includes/extensions/math.lua
Labels: improvement
