Repository Facepunch/garrysmod, pull requests merged in 2020-10, with the labels that each got.

#1693 Add list.GetTable()
  garrysmod/lua/includes/modules/list.lua
Labels: Addition

#1276 Combine two weapons.Register ents loops
  garrysmod/lua/includes/modules/weapons.lua
Labels: Enhancement

#1288 Add player_manager.GetPlayerClasses() and PLAYER:ClassChanged()
  garrysmod/lua/includes/modules/player_manager.lua
Labels: Addition

#1735 [TTT] Distinguish Brazilian Portuguese and European Portuguese
  garrysmod/gamemodes/terrortown/gamemode/lang/brazilian_portuguese.lua
Labels: TTT

#1736 [TTT] Change "Português brasileiro" to "Português (Brasil)"
  garrysmod/gamemodes/terrortown/gamemode/lang/brazilian_portuguese.lua
Labels: TTT
