Repository Facepunch/garrysmod, pull requests merged in 2020-09, with the labels that each got.

#1690 Added undo for weapons
  garrysmod/gamemodes/sandbox/gamemode/commands.lua
Labels: Improvement

#1692 Add NiceText to the undo table
  garrysmod/lua/includes/modules/undo.lua
Labels: Improvement

#1719 Cancel fists melee attack on holster
  garrysmod/lua/weapons/weapon_fists.lua
Labels: Fix

#1720 Allow select Post Processing effects to work with RenderTargets
  garrysmod/lua/postprocess/bloom.lua
  garrysmod/lua/postprocess/color_modify.lua
  garrysmod/lua/postprocess/sharpen.lua
  garrysmod/lua/postprocess/sobel.lua
  garrysmod/lua/postprocess/sunbeams.lua
  garrysmod/lua/postprocess/texturize.lua
  garrysmod/lua/postprocess/toytown.lua
Labels: Fix

#1725 [TTT] Minor changes to portuguese.lua
  garrysmod/gamemodes/terrortown/gamemode/lang/portuguese.lua
Labels: TTT
