Repository Facepunch/garrysmod, pull requests merged in 2020-11, with the labels that each got.

#1488 Fixed entity function type consistency
  garrysmod/lua/includes/extensions/entity.lua
Labels: Enhancement

#1348 Allow weapons with a CalcView function to work with player_manager view overrides
  garrysmod/gamemodes/base/gamemode/cl_init.lua
Labels: Fix

#1307 Added weapons/scripted_ents.PreRegistered hook
  garrysmod/lua/includes/modules/scripted_ents.lua
  garrysmod/lua/includes/modules/weapons.lua
Labels: Addition

#1716 Remove string.__index error
  garrysmod/lua/includes/extensions/string.lua
Labels: Enhancement

#1742 list.Add should return the index the object was placed at
  garrysmod/lua/includes/modules/list.lua
Labels: Enhancement

#1745 Allow null ply in MakeVehicle
  garrysmod/gamemodes/sandbox/gamemode/commands.lua
Labels: Fix
