Repository Facepunch/garrysmod, pull requests merged in 2020-04, with the labels that each got.

#1649 TTT: fix "select language" string
  garrysmod/gamemodes/terrortown/gamemode/lang/german.lua
  garrysmod/gamemodes/terrortown/gamemode/lang/portuguese.lua
  garrysmod/gamemodes/terrortown/gamemode/lang/russian.lua
  garrysmod/gamemodes/terrortown/gamemode/lang/spanish.lua
  garrysmod/gamemodes/terrortown/gamemode/lang/swedish.lua
  garrysmod/gamemodes/terrortown/gamemode/lang/tradchinese.lua
Labels: TTT

#1653 [TTT] Additional language fixes
  garrysmod/gamemodes/terrortown/gamemode/lang/italian.lua
  garrysmod/gamemodes/terrortown/gamemode/lang/tradchinese.lua
Labels: TTT

#1487 Ammo lib update
  garrysmod/lua/includes/extensions/game.lua
Labels: improvement

#1527 Add effects.GetList
  garrysmod/lua/includes/modules/effects.lua
Labels: addition
