Repository Facepunch/garrysmod, pull requests merged in 2021-03, with the labels that each got.

#1776 Update weapon_zm_carry.lua
  garrysmod/gamemodes/terrortown/entities/weapons/weapon_zm_carry.lua
Labels: TTT

#1775 Fix theme issues with DMenuOptions foreground text color
  garrysmod/lua/vgui/dmenuoption.lua
Labels: Fix

#1780 Fix the effects of karma on damage
  garrysmod/gamemodes/terrortown/gamemode/karma.lua
Labels: TTT

#1771 [TTT - PT-BR Translation] Changes to the highlights and to the AFK message
  garrysmod/gamemodes/terrortown/gamemode/lang/brazilian_portuguese.lua
Labels: TTT

#1779 Fix cookie lib cache
  garrysmod/lua/includes/modules/cookie.lua
Labels: Fix

#1781 Upload Japanese Translation for TTT
  garrysmod/gamemodes/terrortown/gamemode/lang/japanese.lua
Labels: TTT

#1783 code smell
  garrysmod/lua/matproxy/player_color.lua
Labels: Enhancement
