Repository Facepunch/garrysmod, pull requests merged in 2021-12, with the labels that each got.

#1830 Additional check for TableInherit function
  garrysmod/lua/includes/modules/scripted_ents.lua
Labels: Fix

#1844 add math.DistToSqr
  garrysmod/lua/includes/extensions/math.lua
Labels: Addition

#1513 Optimized string.Comma.
  garrysmod/lua/includes/extensions/string.lua
Labels: Enhancement

#1800 Add new types to AccessorFunc
  garrysmod/lua/includes/util.lua
Labels: Addition

#1869 [TTT] Add hook for last words
  garrysmod/gamemodes/terrortown/gamemode/gamemsg.lua
Labels: TTT
