Repository Facepunch/garrysmod, pull requests merged in 2022-08, with the labels that each got.

#1408 Fixed nil player being passed to ENT.PostEntityPaste
  garrysmod/lua/includes/modules/duplicator.lua
Labels: Enhancement

#1724 Reload spawn menu when gmod_language changes
  garrysmod/gamemodes/sandbox/gamemode/spawnmenu/spawnmenu.lua
Labels: Enhancement

#1525 Add option to make hands skin match player skin
  garrysmod/gamemodes/base/gamemode/player.lua
  garrysmod/lua/includes/modules/player_manager.lua
Labels: Addition

#1867 Add string.StartsWith
  garrysmod/lua/includes/extensions/string.lua
Labels: Addition

#1903 TTT: Remove ASS
  garrysmod/gamemodes/terrortown/gamemode/cl_voice.lua
Labels: TTT

#1902 Add canvas IsValid check to dragndrop
  garrysmod/lua/includes/extensions/client/panel/dragdrop.lua
Labels: Fix

#1885 Added support for Color's with table sanitization
  garrysmod/lua/includes/extensions/table.lua
Labels: Enhancement

#1896 Add `util.IsBinaryModuleInstalled`
  garrysmod/lua/includes/extensions/util.lua
Labels: Addition

#1910 TTT: Add ukrainian.lua
  garrysmod/gamemodes/terrortown/gamemode/lang/ukrainian.lua
Labels: TTT

#1909 TTT: change "sec" to "seconds"
  garrysmod/gamemodes/terrortown/gamemode/lang/brazilian_portuguese.lua
  garrysmod/gamemodes/terrortown/gamemode/lang/english.lua
Labels: TTT
