Repository Facepunch/garrysmod, pull requests merged in 2022-06, with the labels that each got.

#1891 Fix CollapseKeyValue docstring
  garrysmod/lua/includes/extensions/table.lua
Labels: Fix

#1674 Fixed lingering toolgun ghost when using Player:SelectWeapon in multiplayer
  garrysmod/gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua
Labels: Fix

#1863 Fix entity spawning out of bounds
  garrysmod/gamemodes/sandbox/gamemode/commands.lua
Labels: Fix

#1888 Add math.SnapTo
  garrysmod/lua/includes/extensions/math.lua
Labels: Addition

#1845 Redrawing of ping icons
  garrysmod/html/img/rank1.png
  garrysmod/html/img/rank2.png
  garrysmod/html/img/rank3.png
  garrysmod/html/img/rank4.png
  garrysmod/html/img/rank5.png
Labels: Enhancement
