Repository Facepunch/garrysmod, pull requests merged in 2023-09, with the labels that each got.

#1851 Utilize The close method in various places and add removeing option
  garrysmod/lua/vgui/dcombobox.lua
Labels: Addition, Enhancement

#1872 Implement some improvements for material select
  garrysmod/lua/vgui/matselect.lua
Labels: Enhancement

#1926 Add HL1 ground turrets
  garrysmod/gamemodes/sandbox/gamemode/commands.lua
  garrysmod/lua/autorun/base_npcs.lua
Labels: Addition

#2010 Reduce player __index calls in animations
  garrysmod/gamemodes/base/gamemode/animations.lua
Labels: Enhancement

#1987 Add SWEP/SENT.ClassNameOverride
  garrysmod/lua/includes/modules/scripted_ents.lua
  garrysmod/lua/includes/modules/weapons.lua
Labels: Addition
