Repository Facepunch/garrysmod, pull requests merged in 2023-04, with the labels that each got.

#1950 use snd_musicvolume instead of volume for loading screens
  garrysmod/lua/menu/loading.lua
Labels: Enhancement

#1949 TTT: Fix ironsight position in singleplayer.
  garrysmod/gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
Labels: TTT, Fix

#1936 updated IncludeCS to return include()... undeprecation? 🥺
  garrysmod/lua/includes/util.lua
Labels: Enhancement

#1954 Crop DButton's image size if it's too big
  garrysmod/lua/vgui/dbutton.lua
Labels: Fix

#1734 Create the Derma Icon Browser
  garrysmod/lua/derma/derma_icon_browser.lua
  garrysmod/lua/derma/init.lua
  garrysmod/lua/vgui/diconbrowser.lua
Labels: Addition

#1943 Refactor weapon_medkit
  garrysmod/lua/weapons/weapon_medkit.lua
Labels: Enhancement

#1927 Menu Support for `util.IsBinaryModuleInstalled`
  garrysmod/lua/includes/extensions/util.lua
Labels: Enhancement

#1875 Add the ability to override Tooltip's delay per panel
  garrysmod/lua/includes/extensions/client/panel.lua
  garrysmod/lua/vgui/dtooltip.lua
Labels: Addition, Enhancement

#1953 Added vgui.Exists( `string` classname )
  garrysmod/lua/includes/extensions/client/panel/scriptedpanels.lua
Labels: Addition

#1959 TTT: fix effect_fn being permanent (causes physics crashes)
  garrysmod/gamemodes/terrortown/gamemode/corpse.lua
Labels: TTT
