Repository Facepunch/garrysmod, pull requests merged in 2023-10, with the labels that each got.

#1106 net.ReadPlayer
  garrysmod/lua/includes/extensions/net.lua
Labels: Addition

#2017 Update Team Fortress 2 map categories
  garrysmod/lua/menu/getmaps.lua
Labels: Enhancement

#1731 Add ents/player iterators
  garrysmod/lua/includes/extensions/ents.lua
  garrysmod/lua/includes/extensions/player.lua
Labels: Addition

#1509 Add string.CardinalToOrdinal
  garrysmod/lua/includes/extensions/string.lua
Labels: Addition

#1158 UV support for killicons
  garrysmod/lua/includes/modules/killicon.lua
Labels: Addition

#1866 Add sequential parameter to net.Read/WriteTable
  garrysmod/lua/includes/extensions/net.lua
Labels: Addition, Enhancement

#2020 Clear DOF_Ents on DOF_Kill
  garrysmod/lua/postprocess/dof.lua
Labels: Fix

#1754 Use Brackets for keys in PrintTable
  garrysmod/lua/includes/util.lua
Labels: Enhancement

#2023 TTT: Prevent tttbase Lua errors with NPCs
  garrysmod/gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
Labels: TTT

#2022 Add PreRegisterTOOL hook
  garrysmod/gamemodes/sandbox/entities/weapons/gmod_tool/stool.lua
Labels: Addition
