Repository Facepunch/garrysmod, pull requests merged in 2023-11, with the labels that each got.

#2018 Make it easier to click on addons in the Addons list
  garrysmod/html/js/menu/control.Addons.js
  garrysmod/html/template/addon_list.html
Labels: Enhancement

#1685 Add CanCreateUndo hook
  garrysmod/lua/includes/modules/undo.lua
Labels: Addition

#2001 Add custom icons for tree nodes in some spawnmenu categories
  garrysmod/gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contenttypes/entities.lua
  garrysmod/gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contenttypes/npcs.lua
  garrysmod/gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contenttypes/vehicles.lua
  garrysmod/gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contenttypes/weapons.lua
Labels: Addition

#2026 Fix GetHighestKey not choosing anything if values are all 0
  garrysmod/html/js/menu/control.Servers.js
Labels: Fix

#2025 Bug Fix: Infinite loop on string.Comma when second parameter is numerical.
  garrysmod/lua/includes/extensions/string.lua
Labels: Fix

#1938 Add math.Factorial
  garrysmod/lua/includes/extensions/math.lua
Labels: Addition

#1254 Allow multiple hooks to modify the bullet structure
  garrysmod/gamemodes/base/gamemode/shared.lua
Labels: Addition

#1890 Replaced util.TraceLine by util.TraceHull for tool traces. Fixes trace bypassing parented props
  garrysmod/gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua
Labels: Enhancement

#1787 DT/NetworkVar Changes
  garrysmod/lua/includes/extensions/entity.lua
Labels: Addition, Enhancement

#2028 Added Turkish Language [NEW]
  garrysmod/gamemodes/terrortown/gamemode/lang/turkish.lua
Labels: TTT, Addition

#1951 Add option to force override child tables in table.Merge
  garrysmod/lua/includes/extensions/table.lua
Labels: Addition

#2021 Polyfill table.move for 32-bit Gmod
  garrysmod/lua/includes/extensions/table.lua
Labels: Addition
