Repository Facepunch/garrysmod, pull requests merged in 2023-07, with the labels that each got.

#1986 Update weapon_ttt_phammer.lua
  garrysmod/gamemodes/terrortown/entities/weapons/weapon_ttt_phammer.lua
Labels: TTT

#1983 TTT: Fix broken sound cue and make it toggleable.
  garrysmod/gamemodes/terrortown/gamemode/cl_msgstack.lua
Labels: TTT

#1197 DPanPanel
  garrysmod/lua/includes/vgui_base.lua
  garrysmod/lua/vgui/dpanpanel.lua
Labels: Addition

#1294 Add CHSpline
  garrysmod/lua/includes/util.lua
Labels: Addition

#1580 Replaced usages of 'Player.UniqueID' with 'Player.AccountID' function
  garrysmod/gamemodes/base/gamemode/obj_player_extend.lua
  garrysmod/lua/includes/modules/numpad.lua
Labels: Enhancement

#1998 Make TTT notification sound default off and add a setting for it.
  garrysmod/gamemodes/terrortown/gamemode/cl_help.lua
  garrysmod/gamemodes/terrortown/gamemode/cl_msgstack.lua
  garrysmod/gamemodes/terrortown/gamemode/lang/english.lua
Labels: TTT
