Repository Facepunch/garrysmod, pull requests merged in 2023-01, with the labels that each got.

#1921 Remove useless varargs
  garrysmod/lua/includes/extensions/client/panel/scriptedpanels.lua
Labels: Fix

#1912 Fix tooltip height position miscalculation with newlines.
  garrysmod/lua/vgui/dtooltip.lua
Labels: Fix

#1924 Fix markup alignment inconsistency
  garrysmod/lua/includes/modules/markup.lua
Labels: Fix

#1916 Fix word break for addon descriptions
  garrysmod/html/css/Workshop.css
Labels: Enhancement

#1917 If hud is disabled don't show lua error messages
  garrysmod/lua/menu/errors.lua
Labels: Enhancement

#1925 Update string.lua
  garrysmod/lua/includes/extensions/string.lua
Labels: Addition

#1609 Optimize some points
  garrysmod/gamemodes/base/entities/entities/base_ai/tasks.lua
  garrysmod/gamemodes/base/entities/entities/base_entity/outputs.lua
  garrysmod/gamemodes/base/entities/entities/base_nextbot/sv_nextbot.lua
  garrysmod/gamemodes/base/entities/entities/ragdoll_motion.lua
  garrysmod/gamemodes/base/gamemode/animations.lua
  garrysmod/gamemodes/base/gamemode/cl_deathnotice.lua
  garrysmod/gamemodes/base/gamemode/cl_init.lua
  garrysmod/gamemodes/base/gamemode/cl_scoreboard.lua
  garrysmod/gamemodes/base/gamemode/player.lua
  garrysmod/gamemodes/sandbox/entities/weapons/gmod_tool/stool.lua
  garrysmod/gamemodes/sandbox/entities/weapons/gmod_tool/stools/camera.lua
  garrysmod/gamemodes/sandbox/entities/weapons/gmod_tool/stools/faceposer.lua
  garrysmod/gamemodes/sandbox/entities/weapons/gmod_tool/stools/material.lua
  garrysmod/gamemodes/sandbox/entities/weapons/gmod_tool/stools/paint.lua
  garrysmod/gamemodes/sandbox/gamemode/cl_search_models.lua
  garrysmod/gamemodes/sandbox/gamemode/editor_player.lua
  garrysmod/gamemodes/sandbox/gamemode/persistence.lua
  garrysmod/gamemodes/sandbox/gamemode/player_extension.lua
  garrysmod/gamemodes/sandbox/gamemode/spawnmenu/controls/preset_editor.lua
  garrysmod/gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contentcontainer.lua
  garrysmod/gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contentsearch.lua
  garrysmod/gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contenttypes/addonprops.lua
  garrysmod/gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contenttypes/custom.lua
  garrysmod/gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contenttypes/dupes.lua
  garrysmod/gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contenttypes/gameprops.lua
  garrysmod/gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contenttypes/saves.lua
  garrysmod/gamemodes/sandbox/gamemode/spawnmenu/toolpanel.lua
  garrysmod/lua/includes/extensions/client/panel.lua
  garrysmod/lua/includes/extensions/client/panel/selections.lua
  garrysmod/lua/includes/extensions/ents.lua
  garrysmod/lua/includes/extensions/player.lua
  garrysmod/lua/includes/gmsave.lua
  garrysmod/lua/includes/modules/duplicator.lua
  garrysmod/lua/includes/modules/effects.lua
  garrysmod/lua/includes/modules/scripted_ents.lua
  garrysmod/lua/includes/modules/team.lua
  garrysmod/lua/includes/modules/usermessage.lua
  garrysmod/lua/includes/modules/weapons.lua
  garrysmod/lua/includes/modules/widget.lua
  garrysmod/lua/includes/util.lua
  garrysmod/lua/includes/util/workshop_files.lua
  garrysmod/lua/menu/demo_to_video.lua
  garrysmod/lua/menu/menu_demo.lua
  garrysmod/lua/menu/menu_dupe.lua
  garrysmod/lua/menu/menu_save.lua
  garrysmod/lua/vgui/dcategorycollapse.lua
  garrysmod/lua/vgui/dcategorylist.lua
  garrysmod/lua/vgui/dcolorpalette.lua
  garrysmod/lua/vgui/dfilebrowser.lua
  garrysmod/lua/vgui/diconbrowser.lua
  garrysmod/lua/vgui/diconlayout.lua
  garrysmod/lua/vgui/dmenu.lua
  garrysmod/lua/vgui/dtilelayout.lua
  garrysmod/lua/vgui/dtree_node.lua
Labels: Enhancement

#1761 Add translations for Limit and Cleanup hints
  garrysmod/gamemodes/sandbox/gamemode/cl_init.lua
Labels: Enhancement

#1299 Allow weapons and entities to set their own classname
  garrysmod/lua/includes/modules/scripted_ents.lua
  garrysmod/lua/includes/modules/weapons.lua
Labels: Enhancement

#1793 Call net.Receive "editvariable" once outside InstallDataTable
  garrysmod/lua/includes/extensions/entity.lua
Labels: Enhancement

#1929 TTT `+zoom` fix
  garrysmod/gamemodes/terrortown/gamemode/cl_keys.lua
Labels: TTT

#1480 Add string.Interpolate
  garrysmod/lua/includes/extensions/string.lua
Labels: Addition

#1812 A few string lib optimizations
  garrysmod/lua/includes/extensions/string.lua
Labels: Enhancement

#1728 Improved DAdjustableModelPanel movement
  garrysmod/lua/vgui/dadjustablemodelpanel.lua
Labels: Enhancement

#1739 Toolgun bug fixes
  garrysmod/gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua
  garrysmod/gamemodes/sandbox/entities/weapons/gmod_tool/stool.lua
Labels: Fix
