Repository Facepunch/garrysmod, pull requests merged in 2024-03, with the labels that each got.

#2062 TTT: Use player.Iterator
  garrysmod/gamemodes/terrortown/entities/entities/ttt_c4/shared.lua
  garrysmod/gamemodes/terrortown/entities/entities/ttt_traitor_check.lua
  garrysmod/gamemodes/terrortown/entities/entities/ttt_weapon_check.lua
  garrysmod/gamemodes/terrortown/entities/weapons/weapon_zm_carry.lua
  garrysmod/gamemodes/terrortown/gamemode/admin.lua
  garrysmod/gamemodes/terrortown/gamemode/cl_init.lua
  garrysmod/gamemodes/terrortown/gamemode/cl_popups.lua
  garrysmod/gamemodes/terrortown/gamemode/cl_targetid.lua
  garrysmod/gamemodes/terrortown/gamemode/cl_transfer.lua
  garrysmod/gamemodes/terrortown/gamemode/gamemsg.lua
  garrysmod/gamemodes/terrortown/gamemode/init.lua
  garrysmod/gamemodes/terrortown/gamemode/karma.lua
  garrysmod/gamemodes/terrortown/gamemode/player.lua
  garrysmod/gamemodes/terrortown/gamemode/scoring.lua
  garrysmod/gamemodes/terrortown/gamemode/traitor_state.lua
  garrysmod/gamemodes/terrortown/gamemode/util.lua
  garrysmod/gamemodes/terrortown/gamemode/vgui/sb_main.lua
  garrysmod/gamemodes/terrortown/gamemode/weaponry.lua
Labels: TTT, Enhancement

#2063 TTT: Use net.Read/WritePlayer
  garrysmod/gamemodes/terrortown/gamemode/cl_voice.lua
  garrysmod/gamemodes/terrortown/gamemode/gamemsg.lua
  garrysmod/gamemodes/terrortown/gamemode/player_ext_shd.lua
Labels: TTT, Enhancement

#2067 Make toolgun reload also use util.TraceHull, to make hit detection consistent with primary/secondary
  garrysmod/gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua
Labels: Fix

#2064 TTT: Reduce radar ping bit count
  garrysmod/gamemodes/terrortown/gamemode/cl_radar.lua
  garrysmod/gamemodes/terrortown/gamemode/radar.lua
Labels: TTT

#2066 Updated TTT Turkish Localization
  garrysmod/gamemodes/terrortown/gamemode/lang/turkish.lua
Labels: TTT
