Repository Facepunch/garrysmod, pull requests merged in 2024-04, with the labels that each got.

#2074 [TTT] add TTTShowSearchScreen hook
  garrysmod/gamemodes/terrortown/gamemode/cl_search.lua
Labels: TTT, Addition

#2070 TTT: Update Russian language
  garrysmod/gamemodes/terrortown/content/resource/localization/ru/ttt.properties
  garrysmod/gamemodes/terrortown/gamemode/lang/russian.lua
Labels: TTT, Enhancement

#2072 chore: fix some typos
  bin/garrysmod.fgd
  garrysmod/gamemodes/base/entities/weapons/weapon_base/init.lua
  garrysmod/gamemodes/base/gamemode/animations.lua
Labels: Fix

#2054 Update deprecated GetConVarNumber in weapon_fists
  garrysmod/lua/weapons/weapon_fists.lua
Labels: Enhancement

#2045 Small optimizations to GM:DrawDeathNotice()
  garrysmod/gamemodes/base/gamemode/cl_deathnotice.lua
Labels: Enhancement

#2076 TTT: Replace GetConVarNumber/String
  garrysmod/gamemodes/terrortown/gamemode/corpse.lua
  garrysmod/gamemodes/terrortown/gamemode/init.lua
  garrysmod/gamemodes/terrortown/gamemode/player.lua
  garrysmod/gamemodes/terrortown/gamemode/player_ext.lua
  garrysmod/gamemodes/terrortown/gamemode/player_ext_shd.lua
  garrysmod/gamemodes/terrortown/gamemode/shared.lua
Labels: TTT, Enhancement

#2068 Optimize skypaint matproxy
  garrysmod/lua/matproxy/sky_paint.lua
Labels: Enhancement

#2077 TTT: Replace deprecated GetConVarString usage
  garrysmod/gamemodes/terrortown/gamemode/cl_lang.lua
  garrysmod/gamemodes/terrortown/gamemode/lang_shd.lua
Labels: TTT, Enhancement

#2080 TTT: Optimize ragdoll search network traffic + fix disconnected player networking
  garrysmod/gamemodes/terrortown/gamemode/cl_search.lua
  garrysmod/gamemodes/terrortown/gamemode/corpse.lua
Labels: TTT, Enhancement
