Repository Facepunch/garrysmod, pull requests merged in 2024-09, with the labels that each got.

#2086 util.IntervalTimer
  garrysmod/lua/includes/extensions/util.lua
Labels: Addition

#2111 TTT: Fix and optimize T button rendering
  garrysmod/gamemodes/terrortown/gamemode/cl_tbuttons.lua
Labels: TTT, Fix

#2101 Add a search bar to sequences and make them sort properly.
  garrysmod/gamemodes/sandbox/gamemode/gui/iconeditor.lua
Labels: Addition, Enhancement

#2112 TTT: Update Turkish
  garrysmod/gamemodes/terrortown/gamemode/lang/turkish.lua
Labels: TTT

#2113 Allow for properties to be removed
  garrysmod/lua/includes/modules/properties.lua
Labels: Addition

#2032 Improve SortedPairs even more
  garrysmod/lua/includes/extensions/table.lua
Labels: Enhancement

#2121 [TTT] Fixed attempt to index global 'sam' (a nil value)
  garrysmod/gamemodes/terrortown/gamemode/admin.lua
Labels: TTT, Fix

#2118 Update spanish.lua in the terrortown gamemode
  garrysmod/gamemodes/terrortown/gamemode/lang/spanish.lua
Labels: TTT, Enhancement

#2120 GWEN Performance Improvement
  garrysmod/lua/derma/derma_gwen.lua
Labels: Enhancement
