Repository Facepunch/garrysmod, pull requests merged in 2024-02, with the labels that each got.

#2055 Fix table.Add infinite loop
  garrysmod/lua/includes/extensions/table.lua
Labels: Fix

#2057 Fixed util.IsBinaryModuleInstalled using the wrong path.
  garrysmod/lua/includes/extensions/util.lua
Labels: Fix

#2058 Prevent infinite loop from `panel:SetDragParent`
  garrysmod/lua/includes/extensions/client/panel/dragdrop.lua
Labels: Fix

#2059 [TTT] Fixed can_rag_pin_inno overwriting can_rag_pin in Magneto Stick
  garrysmod/gamemodes/terrortown/entities/weapons/weapon_zm_carry.lua
Labels: TTT, Fix

#2060 TTT: Replace self.Weapon/self.Entity with self
  garrysmod/gamemodes/terrortown/entities/entities/ttt_hat_deerstalker.lua
  garrysmod/gamemodes/terrortown/entities/weapons/weapon_ttt_knife.lua
  garrysmod/gamemodes/terrortown/entities/weapons/weapon_ttt_phammer.lua
  garrysmod/gamemodes/terrortown/entities/weapons/weapon_zm_carry.lua
  garrysmod/gamemodes/terrortown/entities/weapons/weapon_zm_improvised.lua
  garrysmod/gamemodes/terrortown/entities/weapons/weapon_zm_rifle.lua
Labels: TTT, Enhancement
