Repository Facepunch/garrysmod, pull requests merged in 2024-08, with the labels that each got.

#2097 Replace debug.getregistry usage with RegisterMetaTable
  garrysmod/lua/includes/modules/markup.lua
  garrysmod/lua/includes/util/color.lua
Labels: Enhancement

#2102 Typo In Motor Tool
  garrysmod/resource/localization/en/tool.properties
Labels: Fix

#2099 TTT: Fix Swedish chef language borking itself
  garrysmod/gamemodes/terrortown/gamemode/lang/chef.lua
Labels: TTT

#2108 Use `m_pitch` and `m_yaw` for looking around in the taunt camera
  garrysmod/gamemodes/base/gamemode/player_class/taunt_camera.lua
Labels: Enhancement

#2106 Add SAM support to karma banning
  garrysmod/gamemodes/terrortown/gamemode/admin.lua
Labels: TTT
