Repository Facepunch/garrysmod, pull requests merged in 2024-10, with the labels that each got.

#2114 Localization Support For In Game Weapons & Items
  garrysmod/lua/autorun/game_hl2.lua
  garrysmod/resource/localization/en/entities.properties
Labels: Enhancement

#2127 TTT: Updated Turkish Localization
  garrysmod/gamemodes/terrortown/content/resource/localization/tr/ttt.properties
  garrysmod/gamemodes/terrortown/gamemode/lang/turkish.lua
Labels: TTT, Enhancement

#2125 Remove arguments overloading in surface.SetDrawColor
  garrysmod/gamemodes/terrortown/gamemode/cl_hud.lua
  garrysmod/lua/includes/modules/halo.lua
  garrysmod/lua/menu/crosshair_setup.lua
  garrysmod/lua/menu/problems/permissions.lua
  garrysmod/lua/menu/problems/problem_generic.lua
  garrysmod/lua/menu/problems/problem_lua.lua
  garrysmod/lua/skins/default.lua
  garrysmod/lua/vgui/dalphabar.lua
  garrysmod/lua/vgui/dbubblecontainer.lua
  garrysmod/lua/vgui/dcolorbutton.lua
  garrysmod/lua/vgui/dpaneloverlay.lua
  garrysmod/lua/vgui/dproperties.lua
  garrysmod/lua/vgui/dshape.lua
  garrysmod/lua/vgui/prop_vectorcolor.lua
Labels: Enhancement

#2131 Make esc block blue + informational instead of a yellow error
  garrysmod/lua/menu/errors.lua
Labels: Enhancement

#2129 Localization Support for Options
  garrysmod/resource/OptionsSubAudio.res
  garrysmod/resource/OptionsSubGModLegal.res
  garrysmod/resource/gameui_english.txt
  garrysmod/resource/garrysmod_english.txt
  garrysmod/scripts/kb_act.lst
Labels: Enhancement

#2135 TTT: Fix DoPlayerDeath not running twice on DyingShot
  garrysmod/gamemodes/terrortown/gamemode/player.lua
Labels: TTT, Fix

#2137 Add spawnicon safe check in new SWEP autorefresh thing to prevent errors with certain addons
  garrysmod/gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contenttypes/weapons.lua
Labels: Fix

#2132 update german translation
  garrysmod/gamemodes/terrortown/gamemode/lang/german.lua
Labels: TTT, Enhancement

#2078 Reduced bits used by net.Read/WritePlayer based on maxplayers
  garrysmod/lua/includes/extensions/net.lua
Labels: Enhancement

#2044 Fortress Forever + NeoTokyo support: Info_ff_teamspawn
  garrysmod/gamemodes/base/entities/entities/info_ff_teamspawn.lua
  garrysmod/gamemodes/base/entities/entities/info_player_attacker.lua
  garrysmod/gamemodes/base/entities/entities/info_player_defender.lua
  garrysmod/gamemodes/base/gamemode/player.lua
  garrysmod/lua/menu/getmaps.lua
Labels: Addition

#2139 TTT: Allow workshop addons to pack rearm scripts
  garrysmod/gamemodes/terrortown/gamemode/ent_replace.lua
Labels: TTT, Fix
