Repository Facepunch/garrysmod, pull requests merged in 2025-05, with the labels that each got.

#2284 Fix lua error
  garrysmod/gamemodes/sandbox/entities/weapons/gmod_tool/stools/creator.lua
Labels: Fix

#2285 Remove default return in WorldPickerMouseDisable
  garrysmod/lua/includes/extensions/util/worldpicker.lua
Labels: Fix

#2287 Minor improved cam.Start2D
  garrysmod/lua/includes/extensions/client/render.lua
Labels: Enhancement

#2205 Add list.GetEntry
  garrysmod/lua/includes/modules/list.lua
Labels: Addition

#2268 Add list.Remove helper function
  garrysmod/lua/includes/modules/list.lua
Labels: Addition

#2201 type function in lua
  garrysmod/lua/includes/util.lua
Labels: Enhancement, Requires engine changes
