Repository Facepunch/garrysmod, pull requests merged in 2025-07, with the labels that each got.

#2321 Fix tooltip fadeout animation
  garrysmod/gamemodes/base/entities/weapons/weapon_base/cl_init.lua
Labels: Fix

#2319 lights.rad: episodic additions
  garrysmod/lights.rad
Labels: Enhancement

#2324 Prevent DAdjustableModelPanel from handling MMB presses
  garrysmod/lua/vgui/dadjustablemodelpanel.lua
Labels: Enhancement

#2325 Add functions GetValue1(), GetValue2(), GetValues() - CtrlNumPad
  garrysmod/gamemodes/sandbox/gamemode/spawnmenu/controls/ctrlnumpad.lua
Labels: Addition

#2331 Minor improvement GM:HUDDrawTargetID
  garrysmod/gamemodes/base/gamemode/cl_targetid.lua
Labels: Enhancement

#2338 Remove some content checks
  garrysmod/gamemodes/sandbox/entities/weapons/gmod_tool/stools/thruster.lua
Labels: Enhancement

#2332 Clean-up doubleclicking in menu
  garrysmod/html/js/menu/control.NewGame.js
  garrysmod/html/js/menu/control.Servers.js
  garrysmod/html/template/newgame.html
  garrysmod/html/template/servers.html
Labels: Enhancement

#2341 Server list: Added option to "hide outdated servers"
  garrysmod/html/js/menu/control.Servers.js
  garrysmod/html/template/servers.html
  garrysmod/resource/localization/en/main_menu.properties
Labels: Addition
