Repository Facepunch/garrysmod, pull requests merged in 2025-01, with the labels that each got.

#2179 Fix indentation of the gamemode list items
  garrysmod/html/css/menu/NavBar.css
Labels: Fix

#2178 Improve file.Write function to return success status
  garrysmod/lua/includes/extensions/file.lua
Labels: Enhancement

#2153 Added Missing Strings
  garrysmod/gamemodes/base/entities/entities/npc_tf2_ghost.lua
  garrysmod/gamemodes/base/entities/weapons/weapon_base/cl_init.lua
  garrysmod/gamemodes/sandbox/entities/entities/edit_fog.lua
  garrysmod/gamemodes/sandbox/entities/entities/edit_sky.lua
  garrysmod/gamemodes/sandbox/entities/entities/edit_sun.lua
  garrysmod/gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contenttypes/custom.lua
  garrysmod/gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contenttypes/entities.lua
  garrysmod/gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contenttypes/npcs.lua
  garrysmod/gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contenttypes/postprocess.lua
  garrysmod/gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contenttypes/vehicles.lua
  garrysmod/lua/autorun/base_npcs.lua
  garrysmod/lua/autorun/base_vehicles.lua
  garrysmod/lua/autorun/game_hl2.lua
  garrysmod/lua/entities/sent_ball.lua
  garrysmod/lua/includes/modules/weapons.lua
  garrysmod/lua/menu/getmaps.lua
  garrysmod/lua/postprocess/texturize.lua
  garrysmod/resource/localization/en/main_menu.properties
  garrysmod/resource/localization/en/postprocessing.properties
  garrysmod/resource/localization/en/spawnmenu.properties
Labels: Enhancement

#2188 Mini tool optimization
  garrysmod/gamemodes/sandbox/entities/weapons/gmod_tool/cl_init.lua
Labels: Enhancement

#2186 Add tool copying
  garrysmod/gamemodes/sandbox/gamemode/spawnmenu/toolpanel.lua
Labels: Addition

#2185 Rounding out the news panel
  garrysmod/html/css/menu/Menu.css
Labels: Enhancement

#2180 Use `render.PushRenderTarget` and `render.PopRenderTarget` instead
  garrysmod/lua/includes/extensions/client/render.lua
  garrysmod/lua/postprocess/bloom.lua
  garrysmod/lua/postprocess/frame_blend.lua
  garrysmod/lua/postprocess/motion_blur.lua
Labels: Enhancement

#2107 Improvement skypaint matproxy
  garrysmod/lua/matproxy/sky_paint.lua
Labels: Enhancement

#1697 remove server is full rating penalty
  garrysmod/html/js/menu/control.Servers.js
Labels: Enhancement

#2167 Optimize ```ents.FindByClassAndParent```
  garrysmod/lua/includes/extensions/ents.lua
Labels: Enhancement

#2183 Frontend Speedup
  garrysmod/html/js/menu/control.Dupes.js
  garrysmod/html/js/menu/control.Saves.js
  garrysmod/html/js/svc.Tranny.js
  garrysmod/html/js/thirdparty/jquery-color.js
  garrysmod/html/js/thirdparty/jquery-ui.js
  garrysmod/html/js/thirdparty/jquery.js
  garrysmod/html/loading.html
  garrysmod/html/menu.html
  garrysmod/html/template/addon_list.html
  garrysmod/html/template/demos.html
  garrysmod/html/template/dupes.html
  garrysmod/html/template/newgame.html
  garrysmod/html/template/saves.html
  garrysmod/html/template/servers.html
Labels: Enhancement

#2083 Don't draw effect rings w/gravgun equipped.
  garrysmod/gamemodes/base/entities/entities/prop_effect.lua
Labels: Enhancement

#2136 Color manipulation methods
  garrysmod/lua/includes/util/color.lua
Labels: Addition

#2194 Updated deprecated CPanel calls (Continuation & Conclusion)
  garrysmod/gamemodes/sandbox/gamemode/spawnmenu/controlpanel.lua
  garrysmod/lua/autorun/utilities_menu.lua
  garrysmod/lua/includes/modules/cleanup.lua
  garrysmod/lua/includes/modules/undo.lua
  garrysmod/lua/postprocess/bloom.lua
  garrysmod/lua/postprocess/color_modify.lua
  garrysmod/lua/postprocess/dof.lua
  garrysmod/lua/postprocess/frame_blend.lua
  garrysmod/lua/postprocess/motion_blur.lua
  garrysmod/lua/postprocess/overlay.lua
  garrysmod/lua/postprocess/sharpen.lua
  garrysmod/lua/postprocess/sobel.lua
  garrysmod/lua/postprocess/stereoscopy.lua
  garrysmod/lua/postprocess/sunbeams.lua
  garrysmod/lua/postprocess/toytown.lua
Labels: Enhancement

#2197 SetCreator for NPCs on spawn
  garrysmod/gamemodes/sandbox/gamemode/commands.lua
Labels: Enhancement
