Repository Facepunch/garrysmod, pull requests merged in 2025-04, with the labels that each got.

#2262 [TTT] Fix incosistency for default values
  garrysmod/gamemodes/terrortown/terrortown.txt
Labels: TTT, Fix

#2248 Make Spawn_ functions return the spawned entity
  garrysmod/gamemodes/sandbox/gamemode/commands.lua
Labels: Enhancement

#2264 [TTT] fix players sometimes being revealed as dead when they chat/voicechat right as they die (again)
  garrysmod/gamemodes/terrortown/gamemode/cl_voice.lua
Labels: TTT, Fix

#2275 TTT: Added The New Line (TR L10n)
  garrysmod/gamemodes/terrortown/content/resource/localization/tr/ttt.properties
Labels: TTT, Enhancement

#2273 Make team.NumPlayers mildly less slow
  garrysmod/lua/includes/modules/team.lua
Labels: Enhancement
