Repository Facepunch/garrysmod, pull requests merged in 2025-02, with the labels that each got.

#2200 TTT: Magneto-stick DoAttack cleanup
  garrysmod/gamemodes/terrortown/entities/weapons/weapon_zm_carry.lua
Labels: TTT, Enhancement

#2203 TTT: Fix C4/Radio sounds not playing outside of PAS
  garrysmod/gamemodes/terrortown/entities/entities/ttt_c4/shared.lua
  garrysmod/gamemodes/terrortown/entities/entities/ttt_radio.lua
  garrysmod/gamemodes/terrortown/gamemode/entity.lua
Labels: TTT, Fix

#2204 TTT: Fix "CS:S not mounted" warning
  garrysmod/gamemodes/terrortown/gamemode/init.lua
Labels: TTT, Fix

#2212 [TTT] Change holdtypes for consistency with viewmodels
  garrysmod/gamemodes/terrortown/entities/weapons/weapon_ttt_flaregun.lua
  garrysmod/gamemodes/terrortown/entities/weapons/weapon_ttt_glock.lua
  garrysmod/gamemodes/terrortown/entities/weapons/weapon_ttt_sipistol.lua
  garrysmod/gamemodes/terrortown/entities/weapons/weapon_zm_pistol.lua
  garrysmod/gamemodes/terrortown/entities/weapons/weapon_zm_revolver.lua
Labels: TTT

#2215 [TTT] Change L.hstation_hint to better reflect how to use it
  garrysmod/gamemodes/terrortown/gamemode/lang/english.lua
Labels: TTT, Enhancement

#2213 Fix spawnmenu sorting bad tool names
  garrysmod/gamemodes/sandbox/gamemode/spawnmenu/toolpanel.lua
Labels: Fix

#2217 TTT: Update Turkish L10n
  garrysmod/gamemodes/terrortown/gamemode/lang/turkish.lua
Labels: TTT, Enhancement

#2219 Remove unused dependences from menu
  garrysmod/html/dupes.html
  garrysmod/html/js/menu/control.Servers.js
  garrysmod/html/js/menu/menuApp.js
  garrysmod/html/js/thirdparty/angular-ui.js
  garrysmod/html/js/thirdparty/jquery-color.js
  garrysmod/html/js/thirdparty/jquery-ui.js
  garrysmod/html/menu.html
  garrysmod/html/saves.html
  garrysmod/html/template/servers.html
Labels: Enhancement

#2220 TTT: Fix pistols using revolver reload gesture
  garrysmod/gamemodes/terrortown/entities/weapons/weapon_ttt_glock.lua
  garrysmod/gamemodes/terrortown/entities/weapons/weapon_ttt_sipistol.lua
  garrysmod/gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
  garrysmod/gamemodes/terrortown/entities/weapons/weapon_zm_pistol.lua
  garrysmod/gamemodes/terrortown/entities/weapons/weapon_zm_revolver.lua
Labels: TTT, Fix
