Repository Facepunch/garrysmod, pull requests merged in 2025-03, with the labels that each got.

#2225 TTT: Add ttt_filter_role
  garrysmod/gamemodes/terrortown/entities/entities/ttt_filter_role.lua
  garrysmod/gamemodes/terrortown/mapexamples/ttt_traitorcheck.vmf
  garrysmod/gamemodes/terrortown/ttt.fgd
Labels: TTT, Addition

#2221 TTT: Close player volume slider along with scoreboard
  garrysmod/gamemodes/terrortown/gamemode/vgui/sb_row.lua
Labels: TTT, Fix

#2190 Update AngularJS from 1.1.2 to 1.8.2
  garrysmod/html/dupes.html
  garrysmod/html/js/creations/common.js
  garrysmod/html/js/creations/dupes.js
  garrysmod/html/js/creations/saves.js
  garrysmod/html/js/menu/common.js
  garrysmod/html/js/menu/control.Servers.js
  garrysmod/html/js/menu/menuApp.js
  garrysmod/html/js/thirdparty/angular-route.js
  garrysmod/html/js/thirdparty/angular.js
  garrysmod/html/menu.html
  garrysmod/html/saves.html
  garrysmod/html/template/newgame.html
  garrysmod/html/template/servers.html
Labels: Enhancement

#2223 Fix DButton:SetConsoleCommand() not accepting vararg
  garrysmod/lua/vgui/dbutton.lua
Labels: Enhancement

#2207 New Localisation Phrases
  garrysmod/resource/localization/en/community.properties
Labels: Addition

#2229 [TTT] fix players sometimes being revealed as dead when they chat/voicechat right as they die
  garrysmod/gamemodes/base/gamemode/cl_voice.lua
  garrysmod/gamemodes/terrortown/gamemode/cl_voice.lua
Labels: TTT, Fix

#2227 TTT: Let TTTLastWordsMsg hook override default behaviour
  garrysmod/gamemodes/terrortown/gamemode/gamemsg.lua
Labels: TTT, Enhancement

#2210 Cleaner server list layout code & Better display on small screens
  garrysmod/html/css/menu/Servers.css
  garrysmod/html/img/cross.png
  garrysmod/html/img/ranksmall1.png
  garrysmod/html/img/ranksmall2.png
  garrysmod/html/img/ranksmall3.png
  garrysmod/html/img/ranksmall4.png
  garrysmod/html/img/ranksmall5.png
  garrysmod/html/js/menu/control.Servers.js
  garrysmod/html/template/servers.html
Labels: Enhancement

#2240 Make `PLAYER:LimitHit` server only
  garrysmod/gamemodes/sandbox/gamemode/player_extension.lua
Labels: Enhancement

#2238 Added ENT.Information support + 2 fixes for NPC content icons
  garrysmod/gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contenticon.lua
Labels: Addition, Enhancement

#2233 Update base_npcs.lua | Mark the Rocket Propelled Grenade Launcher as a Default Weapon
  garrysmod/lua/autorun/base_npcs.lua
Labels: Enhancement

#2242 TTT: Fix Spelling
  garrysmod/gamemodes/terrortown/gamemode/lang/english.lua
  garrysmod/gamemodes/terrortown/gamemode/lang/turkish.lua
Labels: TTT, Fix

#2244 [TTT] Fixed health station having one more health than intended
  garrysmod/gamemodes/terrortown/entities/entities/ttt_health_station.lua
Labels: TTT, Fix

#2235 TTT: Crosshair Customisation
  garrysmod/gamemodes/terrortown/entities/weapons/weapon_ttt_push.lua
  garrysmod/gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
  garrysmod/gamemodes/terrortown/gamemode/cl_help.lua
  garrysmod/gamemodes/terrortown/gamemode/lang/english.lua
Labels: TTT, Addition

#2249 TTT: Update Turkish L10n (Crosshair Settings)
  garrysmod/gamemodes/terrortown/gamemode/lang/turkish.lua
Labels: TTT, Enhancement

#2254 Updated and fixed french.lua
  garrysmod/gamemodes/terrortown/gamemode/lang/french.lua
Labels: TTT, Enhancement
